require 'prolo.options'
require 'prolo.keymaps'
require 'prolo.plugins'
require 'prolo.colorscheme'
require 'prolo.cmp'
require 'prolo.lsp'
require 'prolo.telescope'
require 'prolo.treesitter'
require 'prolo.autopairs'
require 'prolo.gitsigns'
require 'prolo.nvim-tree'
require 'prolo.bufferline'
require 'prolo.comment'
require 'prolo.toggleterm'

